#+title: notifier.go

Not: It is still under testing.
-----
notifier.̶e̶l̶ go is a basic notification daemon for org-mode agenda, a part of the free software text
editor GNU/Emacs.
-----
* Features
+ Actually works.
+ Emacs independent, so you will get notified even if Emacs is not running by you.
+ Reminder notification before an event.
* Requirements
+ The ~notify-send~ command. (preinstalled in most GNU/Linux distributions)
+ It uses ~kdialog~ in the case of [[https://kde.org/][KDE]].
* Installation
First [[https://go.dev/doc/install][install go]] and make sure that go could be found in your ~$PATH~. Then run:
#+begin_src shell
go get -u github.com/salehmu/notifier.go/notifier
#+end_src

Now ~notifier~ should be located ~$GOPATH/bin/~ (Probably ~~/go/bin~).
* Usage
Auto start the ~notifier~ command with your system, there are many ways to do so, [[https://wiki.archlinux.org/title/autostarting][this]] page
could be useful.
** Configuration
The configuration file should be found at ~~/.config/notifier.go/config.yaml~, and
it is generated automatically.
| Field                | Function.                                                         |
| ~doom~               | Whether you are using Emacs or Doom Emacs[fn:3].                  |
| ~emacsInitFile~      | Emacs ~init.el~ or ~.emacs~ location.                             |
| ~scanInt~            | Scan interval (in seconds) for checking for changes in org-agenda |
| ~beforeNotification~ | Time (in minutes) before getting a reminder of an event.          |
| ~doomScriptLoc~      | ~doomscript~ binary location, in case of doom.                    |
* Why?
Because:
1. It is hard to maintain (sometimes, impossible[fn:1][fn:2]) asynchronous code inside Emacs environment.
2. Debugging Elisp can be painful, compared to other languages. I tired to use
   [[https://github.com/spegoraro/org-alert][spegoraro/org-alert]], [[https://github.com/doppelc/org-notifications][doppelc/org-notifications]], [[https://github.com/akhramov/org-wild-notifier.el][akhramov/org-wild-notifier.el]] and others
   but I couldn't get persistence with any, and I couldn't also debug to tell what was the
   problem. Actually I told myself then it would be easier to rewrite it rather
   than debugging it, and here we go.
* Footnotes

[fn:3] Doom Emacs does not have an ~init.el~, so it requires a different approach. See [[https://github.com/doomemacs/doomemacs/issues/6494][#6494]]

[fn:2] Elisp capability of using threads is often described as 'limited'.

[fn:1] Nothreading. EmacsWiki. Retrieved November 23, 2022, from https://www.emacswiki.org/emacs/NoThreading
